# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [3]:
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
print(np.__version__)
np.show_config()

1.21.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = [

**3. Create a 1D array of zeros of size 10 of type float32**

In [4]:
Z = np.zeros(10, dtype=np.float32)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [6]:
Z = np.zeros((32,12))
# Include your solution below
print("%d bytes" % (Z.size * Z.itemsize))

3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [7]:
Z = np.arange(10,59)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [12]:
a = np.arange(10)
# Include your solution below
Z = a[::-1]
print(Z)

[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [8]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [9]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [ ]:
Z = np.random.random((10,11))
# Include your solution below

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [ ]:
Z = np.ones((5,5))
# Include your solution below

**12. Extract the integer part of the random array of positive numbers below**

In [ ]:
Z = np.random.uniform(0,10,10)
# Include your solution below

**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

**15. Create a random vector of size 10 and sort it**

**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below


**17. Create random vector of size 10 and replace the maximum value by 0**

**18. Find the nearest value from a given value (z) in an array (Z)**

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below

**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [ ]:
Z = np.arange(5)[::-1]
# Include your solution below


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [6]:

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
answer = A * B[:,:,None]
print(answer)



[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [ ]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
def moving_average(x,N = 3):
    #define your function here
    return

a = np.arange(30)
N = 3
print(moving_average(a,N))

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below

**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    