# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
print(np.__version__)
np.show_config()

1.22.1
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

**3. Create a 1D array of zeros of size 10 of type float32**

In [4]:
array = np.zeros(10, dtype=np.float32)
print("1D array of zeros of size 10 of type float32: \n", array)

1D array of zeros of size 10 of type float32: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [5]:
Z = np.zeros((32,12))
# Include your solution below
print("memory size of the array: %d bytes" % (Z.size * Z.itemsize))

memory size of the array: 3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [6]:
array = np.arange(10,59)
print("1D array with values ranging from 10 to 58: \n", array)

1D array with values ranging from 10 to 58: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [7]:
a = np.arange(10)
print("Original vector: \n", a)
# Include your solution below
reversed_vector = a[::-1]
print("Reversed vector: \n", reversed_vector)

Original vector: 
 [0 1 2 3 4 5 6 7 8 9]
Reversed vector: 
 [9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [8]:
matrix = np.arange(9).reshape(3, 3)
print("A 3x3 matrix with values ranging from 0 to 8: \n", matrix)

A 3x3 matrix with values ranging from 0 to 8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [9]:
identity_matrix = np.eye(3)
print("A 3x3 identity matrix: \n", identity_matrix)

A 3x3 identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [10]:
Z = np.random.random((10,11))
# Include your solution below
print("Original array: \n", Z)
maxInColumns = np.amax(Z, axis=0)
print('\n\nMaximum value of each column: \n', maxInColumns)

Original array: 
 [[0.24407119 0.94863186 0.61159379 0.86399158 0.13643569 0.8661504
  0.14537357 0.62552939 0.8605636  0.03449109 0.37159444]
 [0.02714454 0.30956827 0.67970485 0.16777611 0.57940813 0.14712042
  0.13896577 0.08923554 0.98577579 0.34773105 0.85209439]
 [0.14858957 0.69267331 0.80732386 0.57689987 0.31331449 0.57446255
  0.38790918 0.31392945 0.5307086  0.22008364 0.88974239]
 [0.73251982 0.86300013 0.54941055 0.0276037  0.38756484 0.31809374
  0.59527471 0.52056311 0.91930141 0.00519687 0.61673303]
 [0.84769835 0.08635296 0.19507061 0.98779749 0.07180933 0.29435197
  0.84032041 0.60446661 0.09408004 0.50507286 0.56072498]
 [0.3739572  0.23440994 0.4374014  0.79675407 0.5576208  0.54347732
  0.08827082 0.64888894 0.22666971 0.27798403 0.97441698]
 [0.8092115  0.40181396 0.20717489 0.29826352 0.17024091 0.92789563
  0.62465487 0.37691952 0.92453291 0.21256911 0.52224461]
 [0.76803642 0.24935604 0.43404821 0.46317994 0.81944043 0.70410771
  0.47281008 0.81041523 0.4221757

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [11]:
onezero = np.ones((7,7))
onezero[1:-1,1:-1] = 0
print("A 7 * 7 array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else:\n",onezero)

A 7 * 7 array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [12]:
Z = np.ones((5,5))
# Include your solution below
np.pad(Z, ((2, 2), (2, 2)), 'constant', constant_values=((0, 0), (0, 0)))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**12. Extract the integer part of the random array of positive numbers below**

In [13]:
Z = np.random.uniform(0,10,10)
print("A random array of positive numbers: \n", Z)
# Include your solution below
def solution_1(Z):
    return(np.trunc(Z))
#Solution #1
import timeit

s_1 = solution_1(Z)
print('Solution 1: integer part of the random array of positive numbers: \n', s_1)

print('Execution time of solution #1: ')
print(timeit.timeit(lambda : solution_1(Z),  number = 1000000))

A random array of positive numbers: 
 [9.12305681 4.7004366  9.94112867 9.08278677 3.32366932 0.92177485
 4.33225016 4.86441571 0.99362841 6.16347144]
Solution 1: integer part of the random array of positive numbers: 
 [9. 4. 9. 9. 3. 0. 4. 4. 0. 6.]
Execution time of solution #1: 
0.8211754


In [14]:
# Other solutions

def solution_2(Z):
    return(np.floor(Z))

def solution_3(Z):
    return(Z.astype(int))

def solution_4(Z):
    return(Z // 1)

s_2 = solution_2(Z)
print('Solution 2: integer part of the random array of positive numbers: \n', s_2)

print('Execution time of solution #2: ')
print(timeit.timeit(lambda : solution_2(Z),  number = 1000000))

s_3  = solution_3(Z)
print('\nSolution 3: integer part of the random array of positive numbers: \n', s_3)

print('Execution time of solution #3: ')
print(timeit.timeit(lambda : solution_3(Z),  number = 1000000))

s_4 = solution_4(Z)
print('\nSolution 4: integer part of the random array of positive numbers: \n', s_4)

print('Execution time of solution #4: ')
print(timeit.timeit(lambda : solution_4(Z),  number = 1000000))



print('\n\nAs we can see the smallest execution time is for solution #2 and the longest is for solution #4.')

Solution 2: integer part of the random array of positive numbers: 
 [9. 4. 9. 9. 3. 0. 4. 4. 0. 6.]
Execution time of solution #2: 
0.7904182000000004

Solution 3: integer part of the random array of positive numbers: 
 [9 4 9 9 3 0 4 4 0 6]
Execution time of solution #3: 
0.8801107000000004

Solution 4: integer part of the random array of positive numbers: 
 [9. 4. 9. 9. 3. 0. 4. 4. 0. 6.]
Execution time of solution #4: 
2.837701300000001


As we can see the smallest execution time is for solution #2 and the longest is for solution #4.


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [15]:
Z = np.tile(np.arange(0, 5), (5,1))
print('A Matrix with rows with equal values in the range (0,4): \n', Z)

A Matrix with rows with equal values in the range (0,4): 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [16]:
vector = np.linspace(0,1,11 ,endpoint=False)[1:]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [17]:
X = np.random.random(10)
print(X)
X.sort()
print(X)

[0.40576602 0.5534558  0.67083414 0.09946021 0.89572234 0.3095683
 0.88778265 0.22809443 0.90104041 0.18022034]
[0.09946021 0.18022034 0.22809443 0.3095683  0.40576602 0.5534558
 0.67083414 0.88778265 0.89572234 0.90104041]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [18]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.9292597  0.93476463 0.94278022 0.80534647 0.71704598 0.63836989
 0.83236358 1.10950522 0.8032504  0.87621324]
[0.46552191 1.18816552 0.02425606 0.18415891 0.85253807 1.26215129
 0.9344496  0.4833482  0.0441679  1.47957888]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [19]:
vector = np.random.random(10)
print(vector)
vector[vector.argmax()] = 0
print(vector)

[0.745009   0.63405326 0.82555646 0.97624909 0.85223683 0.13206909
 0.87423781 0.20278663 0.44832194 0.26895645]
[0.745009   0.63405326 0.82555646 0.         0.85223683 0.13206909
 0.87423781 0.20278663 0.44832194 0.26895645]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [20]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
print(Z)
nearest = Z.flat[np.abs(Z - z).argmin()]
print(nearest)

[0.41475853 0.52595673 0.34238473 0.54258384 0.47530993 0.4762446
 0.5076554  0.14978576 0.21325277 0.49592768]
0.4959276811234927


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [21]:
Z = np.arange(5)[::-1]
# Include your solution below
## Please note that the given array Z starts from 4 and goes to 0 (not from 5 to 1)!
print(Z)
Z0 = np.zeros((len(Z)-1)*3+(len(Z)))
Z0[::4]=Z
print(Z0)

[4 3 2 1 0]
[4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [22]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
Answer = A * B[:,:,None]
print(Answer)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [23]:
W = np.arange(30).reshape(6,5)
print('The original array: \n', W)
# Include your solution below
W[[0,1]] = W[[1,0]]
print('The array after swapping its first and second rows: \n', W)

The original array: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
The array after swapping its first and second rows: 
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="/Figures/bbox.png" width="150" /> 

In [24]:
def bbox(img):
    #include your solution below
    rows = np.any(img, axis=1) 
    cols = np.any(img, axis=0) 
    r1, r2 = np.where(rows)[0][[0, -1]] 
    c1, c2 = np.where(cols)[0][[0, -1]] 
    return (r1,c1),(r2,c2) 


from PIL import Image

img = np.array(Image.open('Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [25]:
def moving_average(x,N = 3):
    #define your function here
#     answer = np.zeros(int(len(x)/3))
#     answer = sum([x[i::N] for i in range(N)])/N
#     return answer
    answer = np.cumsum(x, dtype=float)
    answer[N:] = answer[N:] - answer[:-N]
    return answer[N - 1::N] / N

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [26]:
C = np.bincount([1,1,2,3,4,4,6])
print('The original array C: \n', C)
# Include yoru solution here
A = np.repeat(np.arange(len(C)), C)
print('An array A such that np.bincount(A) == C \n', A)

The original array C: 
 [0 2 1 1 2 0 1]
An array A such that np.bincount(A) == C 
 [1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?**

In [27]:
Z = np.random.randint(0,10,50)
# Include your solution below
print("Original array:\n",Z)
print('The most frequent value in the array is:',np.bincount(Z).argmax()) #counts the occurrence of each element with bincount and then apply argmax to find the maximum value

Original array:
 [6 6 7 5 9 7 5 2 9 9 7 4 1 9 2 7 6 2 5 7 9 2 0 0 6 0 8 6 0 7 1 2 7 9 3 3 4
 3 3 1 8 5 3 9 7 7 2 2 3 1]
The most frequent value in the array is: 7


**26. Write a function to return the n largest values of an array** 

In [28]:
def nlargest(a,n = 5):
    # Include your solution here
    n_largest_values = a[np.argpartition(-a,n)[:n]]
    return n_largest_values
    

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print("N largest values of an array \n", nlargest(Z,n))  

N largest values of an array 
 [9999 9998 9997 9996 9995]
