# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [5]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [6]:
import numpy as np

**2. Print the numpy version and the configuration**

In [7]:
print(np.__version__)
np.show_config()

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/fatem/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = [

**3. Create a 1D array of zeros of size 10 of type float32**

In [9]:
array = np.zeros(10, dtype=np.float32)
print("1D array of zeros of size 10 of type float32: \n", array)

1D array of zeros of size 10 of type float32: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [10]:
Z = np.zeros((32,12))
# Include your solution below
print("memory size of the array: %d bytes" % (Z.size * Z.itemsize))

memory size of the array: 3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [11]:
array = np.arange(10,59)
print("1D array with values ranging from 10 to 58: \n", array)

1D array with values ranging from 10 to 58: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [12]:
a = np.arange(10)
print("Original vector: \n", a)
# Include your solution below
reversed_vector = a[::-1]
print("Reversed vector: \n", reversed_vector)

Original vector: 
 [0 1 2 3 4 5 6 7 8 9]
Reversed vector: 
 [9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [13]:
matrix = np.arange(9).reshape(3, 3)
print("A 3x3 matrix with values ranging from 0 to 8: \n", matrix)

A 3x3 matrix with values ranging from 0 to 8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [14]:
identity_matrix = np.eye(3)
print("A 3x3 identity matrix: \n", identity_matrix)

A 3x3 identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [35]:
Z = np.random.random((10,11))
# Include your solution below
print("Original array: \n", Z)
maxInColumns = np.amax(Z, axis=0)
print('\n\nMaximum value of each column: \n', maxInColumns)

Original array: 
 [[0.79399542 0.33827901 0.12541992 0.06760865 0.10885459 0.70236886
  0.83792588 0.77260858 0.35899731 0.58184935 0.84949332]
 [0.20280829 0.82535267 0.90285546 0.41337633 0.42790578 0.94785258
  0.76661107 0.31331118 0.80379431 0.3269616  0.74324894]
 [0.61716999 0.28545531 0.58522964 0.24764821 0.34015761 0.16556344
  0.60387589 0.29961359 0.10326246 0.1773301  0.24011288]
 [0.53727734 0.66934026 0.6217553  0.07495985 0.93344787 0.99263226
  0.38632087 0.0925041  0.53999039 0.63016633 0.99981491]
 [0.53468081 0.12303915 0.95118628 0.62900673 0.98633808 0.75765296
  0.14041659 0.80717378 0.0867517  0.61930125 0.53481005]
 [0.96563342 0.96482745 0.7305737  0.14751767 0.54669077 0.48650093
  0.41863841 0.18241802 0.50530681 0.38576346 0.03783865]
 [0.52882827 0.80464858 0.10424094 0.10275554 0.31677435 0.60167213
  0.08708646 0.68151861 0.85497504 0.67733949 0.27460331]
 [0.76110353 0.2192558  0.79859911 0.25930794 0.14009899 0.77950958
  0.25352743 0.20573811 0.828120

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [14]:
onezero = np.ones((7,7))
onezero[1:-1,1:-1] = 0
print("A 7 * 7 array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else:\n",onezero)

A 7 * 7 array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [5]:
Z = np.ones((5,5))
# Include your solution below
np.pad(Z, ((2, 2), (2, 2)), 'constant', constant_values=((0, 0), (0, 0)))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**12. Extract the integer part of the random array of positive numbers below**

In [89]:
Z = np.random.uniform(0,10,10)
print("A random array of positive numbers: \n", Z)
# Include your solution below
def solution_1(Z):
    return(np.trunc(Z))
#Solution #1
import timeit

s_1 = solution_1(Z)
print('Solution 1: integer part of the random array of positive numbers: \n', s_1)

print('Execution time of solution #1: ')
print(timeit.timeit(lambda : solution_1(Z),  number = 1000000))

A random array of positive numbers: 
 [6.34820577e-01 4.64454853e+00 9.97116767e-04 5.28776054e+00
 7.71786938e+00 7.74185541e+00 1.79406964e-01 6.55432229e+00
 6.78894029e+00 6.52509774e+00]
Solution 1: integer part of the random array of positive numbers: 
 [0. 4. 0. 5. 7. 7. 0. 6. 6. 6.]
Execution time of solution #1: 
0.9597461959929205


In [91]:
# Other solutions

def solution_2(Z):
    return(np.floor(Z))

def solution_3(Z):
    return(Z.astype(int))

def solution_4(Z):
    return(Z // 1)

s_2 = solution_2(Z)
print('Solution 2: integer part of the random array of positive numbers: \n', s_2)

print('Execution time of solution #2: ')
print(timeit.timeit(lambda : solution_2(Z),  number = 1000000))

s_3  = solution_3(Z)
print('\nSolution 3: integer part of the random array of positive numbers: \n', s_3)

print('Execution time of solution #3: ')
print(timeit.timeit(lambda : solution_3(Z),  number = 1000000))

s_4 = solution_4(Z)
print('\nSolution 4: integer part of the random array of positive numbers: \n', s_4)

print('Execution time of solution #4: ')
print(timeit.timeit(lambda : solution_4(Z),  number = 1000000))



print('\n\nAs we can see the smallest execution time is for solution #2 and the longest is for solution #4.')

Solution 2: integer part of the random array of positive numbers: 
 [0. 4. 0. 5. 7. 7. 0. 6. 6. 6.]
Execution time of solution #2: 
0.9382257819816004

Solution 3: integer part of the random array of positive numbers: 
 [0 4 0 5 7 7 0 6 6 6]
Execution time of solution #3: 
0.8804330249840859

Solution 4: integer part of the random array of positive numbers: 
 [0. 4. 0. 5. 7. 7. 0. 6. 6. 6.]
Execution time of solution #4: 
2.0101580689952243


As we can see the smallest execution time is for solution #2 and the longest is for solution #4.


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [14]:
Z = np.tile(np.arange(0, 5), (5,1))
print('A Matrix with rows with equal values in the range (0,4): \n', Z)

A Matrix with rows with equal values in the range (0,4): 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [38]:
vector = np.linspace(0,1,11 ,endpoint=False)[1:]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [11]:
X = np.random.random(10)
print(X)
X.sort()
print(X)

[0.85228231 0.96185296 0.03590948 0.2579128  0.77563496 0.21741507
 0.89094423 0.67356839 0.97960322 0.92275102]
[0.03590948 0.21741507 0.2579128  0.67356839 0.77563496 0.85228231
 0.89094423 0.92275102 0.96185296 0.97960322]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [31]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.77830345 0.73410949 0.60450628 0.79520714 0.46011496 0.96610029
 1.04784408 0.80153308 0.96508417 0.82134174]
[0.72562472 0.99544821 0.29426957 0.23053955 0.10781814 1.34160313
 0.71659872 0.53140584 0.47476537 0.69838188]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [32]:
vector = np.random.random(10)
print(vector)
vector[vector.argmax()] = 0
print(vector)

[0.81829431 0.29914834 0.89352253 0.21838901 0.93606521 0.93128504
 0.65142842 0.1064878  0.28093491 0.00328527]
[0.81829431 0.29914834 0.89352253 0.21838901 0.         0.93128504
 0.65142842 0.1064878  0.28093491 0.00328527]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [33]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
print(Z)
nearest = Z.flat[np.abs(Z - z).argmin()]
print(nearest)

[0.14816146 0.3124695  0.48975865 0.25291142 0.06984042 0.9211776
 0.37283763 0.30246928 0.52280245 0.89076596]
0.48975865291601706


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [20]:
Z = np.arange(5)[::-1]
# Include your solution below
## Please note that the given array Z starts from 4 and goes to 0 (not from 5 to 1)!
print(Z)
Z0 = np.zeros((len(Z)-1)*3+(len(Z)))
Z0[::4]=Z
print(Z0)

[4 3 2 1 0]
[4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below



**21. Swap the first and second rows of the 2D array below**

In [20]:
W = np.arange(30).reshape(6,5)
print('The original array: \n', W)
# Include your solution below
W[[0,1]] = W[[1,0]]
print('The array after swapping its first and second rows: \n', W)

The original array: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
The array after swapping its first and second rows: 
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [28]:
def moving_average(x,N = 3):
    #define your function here
#     answer = np.zeros(int(len(x)/3))
#     answer = sum([x[i::N] for i in range(N)])/N
#     return answer
    answer = np.cumsum(x, dtype=float)
    answer[N:] = answer[N:] - answer[:-N]
    return answer[N - 1::N] / N

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [21]:
C = np.bincount([1,1,2,3,4,4,6])
print('The original array C: \n', C)
# Include yoru solution here
A = np.repeat(np.arange(len(C)), C)
print('An array A such that np.bincount(A) == C \n', A)

The original array C: 
 [0 2 1 1 2 0 1]
An array A such that np.bincount(A) == C 
 [1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?**

In [2]:
Z = np.random.randint(0,10,50)
# Include your solution below
print("Original array:\n",Z)
print('The most frequent value in the array is:',np.bincount(Z).argmax()) #counts the occurrence of each element with bincount and then apply argmax to find the maximum value

Original array:
 [5 1 7 8 9 9 2 3 9 5 0 9 6 6 5 1 5 5 7 8 4 3 7 1 7 5 8 9 5 5 7 3 3 8 5 7 3
 7 9 1 6 6 5 0 3 4 0 9 9 6]
The most frequent value in the array is: 5


**26. Write a function to return the n largest values of an array** 

In [3]:
def nlargest(a,n = 5):
    # Include your solution here
    n_largest_values = a[np.argpartition(-a,n)[:n]]
    return n_largest_values
    

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print("N largest values of an array \n", nlargest(Z,n))  

N largest values of an array 
 [9997 9998 9999 9996 9995]
